require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.harpoon")
require("plugins.dap")
require("plugins.neotree")
require("plugins.undotree")
require("plugins.rust-tools")
